
name: listynest
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  http: ^1.5.0
  image_picker: ^1.2.0
  dio: ^5.9.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  shimmer: ^3.0.0
  flutter_secure_storage: ^9.2.4
  cupertino_icons: ^1.0.8
  go_router: ^17.0.0
  intl: ^0.20.2
  firebase_core: ^4.2.1
  firebase_analytics: ^12.0.4
  firebase_auth: ^6.1.2
  firebase_storage: ^13.0.4
  cloud_firestore: ^6.1.0
  firebase_messaging: ^16.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
